// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy8_llzEztgTIF0-CAkf4K5AxquUgkP08',
    appId: '1:601414045311:web:77b02757a72e6073a3b94a',
    messagingSenderId: '601414045311',
    projectId: 'my-weather-app-1954',
    authDomain: 'my-weather-app-1954.firebaseapp.com',
    storageBucket: 'my-weather-app-1954.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7kE-yFHZDCmqBr8MJWlu5tEP8ycwCjrA',
    appId: '1:601414045311:android:5a60269fd0180016a3b94a',
    messagingSenderId: '601414045311',
    projectId: 'my-weather-app-1954',
    storageBucket: 'my-weather-app-1954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjcUoYj38fKVxVz3LHw0QGBwZU3GI9Ec',
    appId: '1:601414045311:ios:500b24043317be73a3b94a',
    messagingSenderId: '601414045311',
    projectId: 'my-weather-app-1954',
    storageBucket: 'my-weather-app-1954.appspot.com',
    iosClientId: '601414045311-pjt7hlalpa1a0uder0km4jkhfk105jk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjcUoYj38fKVxVz3LHw0QGBwZU3GI9Ec',
    appId: '1:601414045311:ios:500b24043317be73a3b94a',
    messagingSenderId: '601414045311',
    projectId: 'my-weather-app-1954',
    storageBucket: 'my-weather-app-1954.appspot.com',
    iosClientId: '601414045311-pjt7hlalpa1a0uder0km4jkhfk105jk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherapp',
  );
}
